classDiagram

    class Post {
        Long id
        String title;
        String content;
    }

    class User {
        Long id
        Name name
        Age age
        String hobby
    }

    class BaseEntity {
        LocalDateTime createdAt
        Long createdBy
    }
