### 유저1 생성
POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
  "name": "bingbong",
  "password": "bingbong",
  "age": 30
}

### 유저1 로그인
POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "name": "bingbong",
  "password": "bingbong"
}

### 내 정보 조회
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NDUxNTUsImV4cCI6MTcwMTY0NTE3NSwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.xKSoLZ5JXdAvWTFLAWifugJ5dBImTm5oJMkp9XOr2THdv8uWmp7ozOrCs4KUtFG1RIFuIxu1kfbEXgr669pDCA

### accessToken 재발급
POST http://localhost:8080/api/v1/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NDUxNDQsImV4cCI6MTcwMTY0NTIwNCwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.V_-7vRaEb_necy5XqQstQVy5RmgGBMB5GKkpfnkN8_GSGkmJYlRCYzz29sRI1tVpA3eRPWlsJDs-zc9RVZ3Yqg

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI2NjIsImV4cCI6MTcwMTYxMjY2MiwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.Y-Ig7xw-S8-eFR_-QrmSAaC29iDfOUy3wFPklVR7O0oKJpIFqbKOqjzRTm1vCbuvQXca0d6nwbr0e8BkD1drdg

{
  "title": "빙봉 제목",
  "content": "빙봉 내용"
}

### 유저2 생성
POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
  "name": "hanna",
  "password": "hannalee",
  "age": 25
}

### 유저2 로그인
POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "name": "hanna",
  "password": "hannalee"
}

### 내 정보 조회
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

{
  "title": "한나 제목",
  "content": "한나 내용"
}

### 남의 게시글 수정
PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

{
  "title": "제목 수정",
  "content": "내용 수정"
}

### 잘못된 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목"
}

### 게시글 전체 조회
GET http://localhost:8080/api/v1/posts?page=-1&size=-1
