### 회원가입
POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "email": "hello@prgrm.com",
  "password": "password1234",
  "passwordConfirm": "password1234",
  "name": "hello",
  "age": 100,
  "hobby": "coding"
}

### 로그인
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "daeng@prgrm.com",
  "password": "password1234"
}

### 관리자 로그인 (Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjExNzAxNjAwNzg5fQ.TtLFqRU4OPS7CMSjUEZBPUP8MdWX8hJgyG210A1rD7s) <- 임시토큰
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin1234"
}



### 본인 정보 조회 (토큰 필요)
GET http://localhost:8080/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTE3MDE1ODA0OTF9.7v_nkqqYJsTRhjcr_C8EOQyZgca2sk7umRdK0haUxiY


### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목 111",
  "content": "게시글 1",
  "authorId": 1
}

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목 222",
  "content": "게시글 2",
  "authorId": 1
}

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목 333",
  "content": "게시글 3",
  "authorId": 1
}

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목 444",
  "content": "게시글 4",
  "authorId": 1
}

### 잘못된 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목",
  "content": "게시글",
  "authorId": 2
}

### 게시글 전체 조회
GET http://localhost:8080/api/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjExNzAxNTg5NjMzfQ.vKG04V7hF7KzpmZofpzK1f6NqOKo7YLhn3_0i2ueXCI
