### 유저1 생성
POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
  "name": "bingbong",
  "password": "bingbong",
  "age": 30
}

### 유저1 로그인
POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "name": "bingbong",
  "password": "bingbong"
}

### 내 정보 조회
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NDk3ODQsImV4cCI6MTcwMTY0OTgwNCwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.A5aI06bePzkIhVGExwbvgFbVGMXTvXjSIuRsygUz6yEd5FDz7A3G8OaRKoS3VBJkbjNLkIjbC4X6VnTCkm2OcA

### accessToken 재발급
POST http://localhost:8080/api/v1/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NDk3ODQsImV4cCI6MTcwMTY0OTg0NCwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.THlu44SufwJjuvn363BK1hBFapF0aLLGuEAg-E9aMB5bPKacacLf1dmaOJhnxF9wPYWuFvyHnpxzMTzOysN1vQ

### 유저가 어드민 API 접근
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NTA5MTEsImV4cCI6MTcwMTY1MDk0MSwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.4kmrzS-87o_yApPoFi9Nu92yr3X7zoSqdMmP1Yos8sSf4ET_k6sVk3nK0gfZ8xYS6raG3g8ANZB-incsyJ0djQ

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE2NDk4MTksImV4cCI6MTcwMTY0OTgzOSwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.x43qxcZJBRCeJ2gcPtkOPgLrjoYeAfL3yRIFXFD30CpTYhQXPT_hR4R_EUsz5U2vd7-SVPMpD0YpWX4zXA0mEQ

{
  "title": "빙봉 제목",
  "content": "빙봉 내용"
}

### 유저2 생성
POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
  "name": "hanna",
  "password": "hannalee",
  "age": 25
}

### 유저2 로그인
POST http://localhost:8080/api/v1/users/sign-in
Content-Type: application/json

{
  "name": "hanna",
  "password": "hannalee"
}

### 내 정보 조회
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

### 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

{
  "title": "한나 제목",
  "content": "한나 내용"
}

### 남의 게시글 수정
PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwcmdybXMiLCJpYXQiOjE3MDE1ODI3MTEsImV4cCI6MTcwMTYxMjcxMSwidXNlcklkIjoyLCJyb2xlcyI6WyJVU0VSIl19.23HAS_4JWVqCk0Kz9otLVA1dEImj1V2ECDDNfwkkb7zxk4zeObu9VlzoU2CJabv2-HIxnj7cehcVUcjyxinCBg

{
  "title": "제목 수정",
  "content": "내용 수정"
}

### 잘못된 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "제목"
}

### 게시글 전체 조회
GET http://localhost:8080/api/v1/posts?page=-1&size=-1
