### 회원가입
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "name": "choeunbi",
  "loginId" : "eunbi",
  "password" : "user1234"
}

### 로그인
POST http://localhost:8080/api/v1/members/sign-in
Content-Type: application/json

{
  "loginId" : "eunbi",
  "password" : "user1234"
}

### 회원 조회
GET http://localhost:8080/api/v1/members/1

### 회원 수정
PUT http://localhost:8080/api/v1/members/1
Content-Type: application/json

{
  "password" : "change1234"
}

### 회원 삭제
DELETE http://localhost:8080/api/v1/members?ids=1

