### 게시물 생성
POST http://localhost:8080/api/v1/posts
Accept: application/json
Content-Type: application/json

{
  "title": "제목",
  "content": "내용",
  "userId": 1
}

### 게시물 수정
PATCH http://localhost:8080/api/v1/posts/1
Accept: application/json
Content-Type: application/json

{
  "title": "제목 수정",
  "content": "내용 수정"
}