ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= 게시판 미션 API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

[[Post-API]]
== Post API

[[게시판-페이징-조회]]
=== 게시판 페이징 조회
operation::post-getAll[snippets='http-request,http-response,response-fields']

[[게시판-단건-조회]]
=== 게시판 단건 조회
operation::post-getDetails[snippets='http-request,path-parameters,http-response,response-fields']

[[게시판-등록]]
[[게시판-등록-성공]]
=== 게시판 등록 성공
==== 게시판 등록
operation::post-create[snippets='http-request,request-fields,http-response,response-fields']

[[게시판-등록-실패]]
=== 게시판 등록 실패
==== 빈 제목인 게시판 등록
operation::post-create-title-fail[snippets='http-request,request-fields,http-response,response-fields']

==== 빈 내용인 게시판 등록
operation::post-create-content-fail[snippets='http-request,request-fields,http-response,response-fields']

[[게시판-수정]]
[[게시판-수정-성공]]
=== 게시판 수정 성공
==== 게시판 수정
operation::post-modify[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[게시판-수정-실패]]
=== 게시판 수정 실패
==== 빈 제목으로 게시판 수정
operation::post-modify-title-fail[snippets='http-request,request-fields,http-response,response-fields']

==== 빈 내용으로 게시판 수정
operation::post-modify-content-fail[snippets='http-request,request-fields,http-response,response-fields']

[[User-API]]
== User API

[[유저-회원가입]]
=== 회원가입
operation::user-join[snippets='http-request,request-fields,http-response']

[[유저-로그인]]
=== 로그인
operation::user-login[snippets='http-request,request-fields,http-response,response-headers']

[[유저-정보조회]]
=== 정보조회
operation::user-getDetails[snippets='http-request,http-response,response-fields']
